//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int StatusID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
