//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public int TreatmentID { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
        public int TreatmentTypeID { get; set; }
    
        public virtual TreatmentType TreatmentType { get; set; }
    }
}
